package agent

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/genai"
)

// TransactionAlert holds the details of an incoming alert.
type TransactionAlert struct {
	AccountID    string  `json:"account_id"`
	Amount       float64 `json:"amount"`
	Currency     string  `json:"currency"`
	Country      string  `json:"country"`
	MerchantType string  `json:"merchant_type"` // e.g. "casino", "retail"
}

// RunAnalysis orchestrates the multi-turn agent loop for investigating a transaction alert.
func (a *Agent) RunAnalysis(ctx context.Context, alert TransactionAlert) (string, error) {
	log.Printf("[Agent Loop] Starting investigation for Account: %s, Amount: %.2f %s, Location: %s, Merchant: %s",
		alert.AccountID, alert.Amount, alert.Currency, alert.Country, alert.MerchantType)

	prompt := fmt.Sprintf(
		"NEW TRANSACTION ALERT FOR INVESTIGATION:\n"+
			"- Account ID: %s\n"+
			"- Amount: %.2f %s\n"+
			"- Country: %s\n"+
			"- Merchant Type: %s\n\n"+
			"Please start the investigation by calling `getCustomerProfile` tool. Then assess risk and decide on action.",
		alert.AccountID, alert.Amount, alert.Currency, alert.Country, alert.MerchantType,
	)

	// We supply clear instructions defining the mathematical anomaly model.
	// Gemini will use these rules during its reasoning turns.
	systemInstruction := "You are a professional, autonomous Fraud Detection Agent.\n\n" +
		"INVESTIGATION WORKFLOW:\n" +
		"1. Retrieve the customer's profile using the `getCustomerProfile` tool with the provided account_id.\n" +
		"2. Evaluate the three anomaly risk factors:\n" +
		"   - Geographic Risk (Vgeo): 1.0 if the transaction country is different from the customer's home country, 0.0 otherwise.\n" +
		"   - Value Risk (Dval): 0.0 if the transaction amount <= customer's typical amount. Otherwise, calculate as (amount - typical_amount) / typical_amount, capped at 1.0.\n" +
		"   - Behavioral Risk (Ibeh): 1.0 if the merchant type is high-risk (e.g. 'casino', 'betting', 'gambling'), 0.0 otherwise.\n" +
		"3. Compute the overall anomaly risk score (Arisk) using the mathematical formula:\n" +
		"   Arisk = 0.4 * Vgeo + 0.4 * Dval + 0.2 * Ibeh\n" +
		"4. Card Suspension Action:\n" +
		"   - If Arisk >= 0.6, you MUST immediately call the `executeCardSuspension` tool to block the card.\n" +
		"   - If Arisk < 0.6, do NOT suspend the card.\n" +
		"5. Present a structured final report containing:\n" +
		"   - The values of Vgeo, Dval, Ibeh\n" +
		"   - The calculated Arisk score\n" +
		"   - The final decision: APPROVED or CARD_SUSPENDED with explanation."

	// Initialize conversation history
	contents := []*genai.Content{
		{
			Role: "user",
			Parts: []*genai.Part{
				{Text: prompt},
			},
		},
	}

	config := &genai.GenerateContentConfig{
		SystemInstruction: &genai.Content{
			Parts: []*genai.Part{
				{Text: systemInstruction},
			},
		},
		Tools: a.Tools,
	}

	// Restrict to max 5 turns to prevent potential infinite loops
	const maxTurns = 5
	for turn := 1; turn <= maxTurns; turn++ {
		// Log the request prompt / tool response sent to the model in the current turn
		logRequest(turn, contents[len(contents)-1])

		log.Printf("[Agent Loop] Invoking Gemini (turn %d)...", turn)
		resp, err := a.Client.Models.GenerateContent(ctx, a.ModelName, contents, config)
		if err != nil {
			return "", fmt.Errorf("error calling Gemini model on turn %d: %w", turn, err)
		}

		if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil {
			return "", fmt.Errorf("received empty content candidate from Gemini model")
		}

		candidate := resp.Candidates[0]
		
		// Log the response generated by the model
		logResponse(turn, candidate.Content)

		// Append model's response (which contains text and/or tool calls) to the conversation history
		contents = append(contents, candidate.Content)

		// Search for FunctionCalls in the model's response parts
		var functionCalls []*genai.FunctionCall
		var textResponse string
		for _, part := range candidate.Content.Parts {
			if part.FunctionCall != nil {
				functionCalls = append(functionCalls, part.FunctionCall)
			}
			if part.Text != "" {
				textResponse += part.Text + "\n"
			}
		}

		// If no tools were called, the agent has successfully concluded its investigation.
		if len(functionCalls) == 0 {
			log.Printf("[Agent Loop] Investigation finalized by the model.")
			return textResponse, nil
		}

		// Execute the requested tools
		var responseParts []*genai.Part
		for _, fc := range functionCalls {
			log.Printf("[Agent Loop] Executing tool '%s' (Call ID: %s)", fc.Name, fc.ID)
			var toolResult map[string]any

			switch fc.Name {
			case "getCustomerProfile":
				accountID, ok := fc.Args["account_id"].(string)
				if !ok {
					toolResult = map[string]any{"error": "missing or invalid account_id parameter"}
				} else {
					profile, err := a.DB.GetCustomerProfile(accountID)
					if err != nil {
						toolResult = map[string]any{"error": err.Error()}
					} else {
						toolResult = map[string]any{
							"account_id":     profile.AccountID,
							"customer_name":  profile.CustomerName,
							"home_country":   profile.HomeCountry,
							"typical_amount": profile.TypicalAmount,
							"card_status":    profile.CardStatus,
						}
					}
				}

			case "executeCardSuspension":
				accountID, ok := fc.Args["account_id"].(string)
				if !ok {
					toolResult = map[string]any{"error": "missing or invalid account_id parameter"}
				} else {
					err := a.DB.SuspendCard(accountID)
					if err != nil {
						toolResult = map[string]any{"error": err.Error()}
					} else {
						toolResult = map[string]any{
							"status":  "success",
							"message": fmt.Sprintf("Card suspended successfully for account %s", accountID),
						}
					}
				}

			default:
				toolResult = map[string]any{"error": fmt.Sprintf("unknown tool call: %s", fc.Name)}
			}

			// Rygorystycznie zachowujemy identyfikator ID dla wywołania funkcji
			respPart := &genai.Part{
				FunctionResponse: &genai.FunctionResponse{
					Name:     fc.Name,
					ID:       fc.ID, // MATCHING ID IS MANDATORY FOR GEMINI 2.5/3.5 API
					Response: toolResult,
				},
			}
			responseParts = append(responseParts, respPart)
		}

		// Return the function execution results as a new turn (role "user")
		contents = append(contents, &genai.Content{
			Role:  "user",
			Parts: responseParts,
		})
	}

	return "", fmt.Errorf("agent failed to complete investigation within %d turns", maxTurns)
}

func logRequest(turn int, content *genai.Content) {
	log.Printf("[GEMINI REQUEST - Turn %d] Role: %s", turn, content.Role)
	for i, part := range content.Parts {
		if part.Text != "" {
			log.Printf("  Part %d (Text):\n%s", i+1, part.Text)
		}
		if part.FunctionResponse != nil {
			log.Printf("  Part %d (Tool Response): %s [ID: %s] -> %+v",
				i+1, part.FunctionResponse.Name, part.FunctionResponse.ID, part.FunctionResponse.Response)
		}
	}
}

func logResponse(turn int, content *genai.Content) {
	log.Printf("[GEMINI RESPONSE - Turn %d] Role: %s", turn, content.Role)
	for i, part := range content.Parts {
		if part.Text != "" {
			log.Printf("  Part %d (Text):\n%s", i+1, part.Text)
		}
		if part.FunctionCall != nil {
			log.Printf("  Part %d (Tool Call Request): %s [ID: %s] Args: %+v",
				i+1, part.FunctionCall.Name, part.FunctionCall.ID, part.FunctionCall.Args)
		}
	}
}
